# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 14:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20151212_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2015, 12, 12, 14, 24, 48, 235491)),
        ),
    ]
