# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.CharField(max_length=5000)),
                ('dateof', models.DateTimeField(verbose_name='Date')),
            ],
        ),
    ]
