# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Input', models.IntegerField()),
                ('Output', models.TextField()),
            ],
        ),
    ]
