# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('name', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_model',
            old_name='Input',
            new_name='input',
        ),
        migrations.RenameField(
            model_name='order_model',
            old_name='Output',
            new_name='output',
        ),
    ]
