#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Fun.Resource", IsApplication=true)]

namespace Fun
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int access = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060031
			public const int ButtonSaveIngredient = 2131099697;
			
			// aapt resource value: 0x7f060000
			public const int CoctailsNotFound = 2131099648;
			
			// aapt resource value: 0x7f060030
			public const int ErrorTextView = 2131099696;
			
			// aapt resource value: 0x7f060014
			public const int IngredientList = 2131099668;
			
			// aapt resource value: 0x7f06000f
			public const int IngredientName = 2131099663;
			
			// aapt resource value: 0x7f060013
			public const int buttomCoctails = 2131099667;
			
			// aapt resource value: 0x7f06000e
			public const int buttonMinus = 2131099662;
			
			// aapt resource value: 0x7f060026
			public const int buttonNew = 2131099686;
			
			// aapt resource value: 0x7f06002a
			public const int buttonNext = 2131099690;
			
			// aapt resource value: 0x7f060010
			public const int buttonPlus = 2131099664;
			
			// aapt resource value: 0x7f060028
			public const int buttonPrevious = 2131099688;
			
			// aapt resource value: 0x7f060022
			public const int buttonSave = 2131099682;
			
			// aapt resource value: 0x7f06000b
			public const int coctailDiscription = 2131099659;
			
			// aapt resource value: 0x7f060003
			public const int coctailImage = 2131099651;
			
			// aapt resource value: 0x7f060015
			public const int coctailImagelist = 2131099669;
			
			// aapt resource value: 0x7f060007
			public const int coctailName = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int coctailsList = 2131099649;
			
			// aapt resource value: 0x7f060025
			public const int descriptionNewCoctail = 2131099685;
			
			// aapt resource value: 0x7f06002f
			public const int editTextAlcoholIngredient = 2131099695;
			
			// aapt resource value: 0x7f06002e
			public const int editTextNameIngredient = 2131099694;
			
			// aapt resource value: 0x7f06001b
			public const int imageCameraView = 2131099675;
			
			// aapt resource value: 0x7f06000a
			public const int imageView1 = 2131099658;
			
			// aapt resource value: 0x7f060029
			public const int ingridientSelectText = 2131099689;
			
			// aapt resource value: 0x7f06002c
			public const int isSelectedIngredient = 2131099692;
			
			// aapt resource value: 0x7f06000d
			public const int linearLayout1 = 2131099661;
			
			// aapt resource value: 0x7f06001f
			public const int linearLayout10 = 2131099679;
			
			// aapt resource value: 0x7f060018
			public const int linearLayout11 = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int linearLayout13 = 2131099673;
			
			// aapt resource value: 0x7f06001c
			public const int linearLayout14 = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int linearLayout15 = 2131099677;
			
			// aapt resource value: 0x7f06001a
			public const int linearLayout16 = 2131099674;
			
			// aapt resource value: 0x7f060020
			public const int linearLayout17 = 2131099680;
			
			// aapt resource value: 0x7f060024
			public const int linearLayout18 = 2131099684;
			
			// aapt resource value: 0x7f060004
			public const int linearLayout2 = 2131099652;
			
			// aapt resource value: 0x7f060017
			public const int linearLayout3 = 2131099671;
			
			// aapt resource value: 0x7f06002b
			public const int linearLayout4 = 2131099691;
			
			// aapt resource value: 0x7f060008
			public const int linearLayout5 = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int linearLayout6 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int linearLayout7 = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int linearLayout8 = 2131099650;
			
			// aapt resource value: 0x7f060027
			public const int linearLayout9 = 2131099687;
			
			// aapt resource value: 0x7f06000c
			public const int listCoctailIngredients = 2131099660;
			
			// aapt resource value: 0x7f060012
			public const int myButton = 2131099666;
			
			// aapt resource value: 0x7f060021
			public const int nameNewCoctail = 2131099681;
			
			// aapt resource value: 0x7f060009
			public const int personCoctailCount = 2131099657;
			
			// aapt resource value: 0x7f06002d
			public const int selectedIngredientListView = 2131099693;
			
			// aapt resource value: 0x7f06001e
			public const int textView1 = 2131099678;
			
			// aapt resource value: 0x7f060023
			public const int textView2 = 2131099683;
			
			// aapt resource value: 0x7f060032
			public const int textView3 = 2131099698;
			
			// aapt resource value: 0x7f060016
			public const int textureView1 = 2131099670;
			
			// aapt resource value: 0x7f060011
			public const int volum = 2131099665;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int CoctailList = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int CoctailView = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int IngredientView = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Main = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int NewCoctail = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int NewIngredient = 2130968581;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int openCamera = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
