# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20151213_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null='allow', on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
    ]
